name = "dm-gateway-bot"
main = "worker.js"
compatibility_date = "2026-04-30"
workers_dev = true

[vars]
ENV_BOT_TOKEN = "123456:AAG***rxkx***LFPfzs
"
ENV_OWNER_ID = "67*****64"

[[kv_namespaces]]
binding = "KV"
#id = "把id前面的#号去掉并用你的KV空间id取代这行字"
