name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --var ENV_BOT_TOKEN:${{ secrets.ENV_BOT_TOKEN }} --var ENV_OWNER_ID:${{ secrets.ENV_OWNER_ID }}